# Generated by Django 4.2.8 on 2024-05-17 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepositProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.CharField(max_length=100)),
                ('fin_prdt_nm', models.CharField(max_length=100)),
                ('fin_co_no', models.CharField(max_length=100)),
                ('kor_co_nm', models.CharField(max_length=100)),
                ('dcls_month', models.CharField(max_length=20)),
                ('dcls_strt_day', models.CharField(max_length=20)),
                ('dcls_end_day', models.CharField(blank=True, max_length=20, null=True)),
                ('fin_co_subm_day', models.CharField(max_length=30)),
                ('join_deny', models.CharField(max_length=5)),
                ('join_member', models.TextField(blank=True, null=True)),
                ('join_way', models.TextField(blank=True, null=True)),
                ('etc_note', models.TextField(blank=True, null=True)),
                ('max_limit', models.IntegerField(blank=True, null=True)),
                ('mtrt_int', models.TextField(blank=True, null=True)),
                ('spcl_cnd', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SavingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.CharField(max_length=100)),
                ('fin_prdt_nm', models.CharField(max_length=100)),
                ('fin_co_no', models.CharField(max_length=100)),
                ('kor_co_nm', models.CharField(max_length=100)),
                ('dcls_month', models.CharField(max_length=20)),
                ('dcls_strt_day', models.CharField(max_length=20)),
                ('dcls_end_day', models.CharField(blank=True, max_length=20, null=True)),
                ('fin_co_subm_day', models.CharField(max_length=30)),
                ('join_deny', models.CharField(max_length=5)),
                ('join_member', models.TextField(blank=True, null=True)),
                ('join_way', models.TextField(blank=True, null=True)),
                ('etc_note', models.TextField(blank=True, null=True)),
                ('max_limit', models.IntegerField(blank=True, null=True)),
                ('mtrt_int', models.TextField(blank=True, null=True)),
                ('spcl_cnd', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SavingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intr_rate', models.FloatField(blank=True, null=True)),
                ('intr_rate2', models.FloatField(blank=True, null=True)),
                ('intr_rate_type', models.CharField(max_length=20)),
                ('intr_rate_type_nm', models.CharField(max_length=20)),
                ('save_trm', models.CharField(max_length=20)),
                ('rsrv_type', models.CharField(max_length=100)),
                ('rsrv_type_nm', models.CharField(max_length=100)),
                ('saving_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.savingproduct')),
            ],
        ),
        migrations.CreateModel(
            name='DepositOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intr_rate', models.FloatField(blank=True, null=True)),
                ('intr_rate2', models.FloatField(blank=True, null=True)),
                ('intr_rate_type', models.CharField(max_length=20)),
                ('intr_rate_type_nm', models.CharField(max_length=20)),
                ('save_trm', models.CharField(max_length=20)),
                ('deposit_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.depositproduct')),
            ],
        ),
    ]
