# Generated by Django 4.2.8 on 2024-05-16 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingoption',
            name='intr_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='savingoption',
            name='intr_rate2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='savingproduct',
            name='dcls_end_day',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
