# Generated by Django 4.2.8 on 2024-05-17 13:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finances', '0002_alter_savingoption_intr_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositproduct',
            name='join_user',
            field=models.ManyToManyField(related_name='join_deposit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='savingproduct',
            name='join_user',
            field=models.ManyToManyField(related_name='join_saving', to=settings.AUTH_USER_MODEL),
        ),
    ]
