# Generated by Django 4.2.8 on 2024-05-19 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("exchanges", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="current",
            name="cur_unit",
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("ttb", models.DecimalField(decimal_places=2, max_digits=10)),
                ("tts", models.DecimalField(decimal_places=2, max_digits=10)),
                ("deal_bas_r", models.DecimalField(decimal_places=2, max_digits=10)),
                ("bkpr", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "current",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exchange_rates",
                        to="exchanges.current",
                    ),
                ),
            ],
            options={
                "unique_together": {("current", "date")},
            },
        ),
    ]
